# https://travis-ci.org/pytorch/pytorch
language: python
python: "3.6"
dist: xenial
sudo: false

install:
  - cp Makefile.template Makefile
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - make codestyle
  - make tests
